# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_managed',
            field=models.BooleanField(default=True),
        ),
    ]
