# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import play.models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_organization_is_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.Project')),
            ],
            options={
                'get_latest_by': 'created_at',
                'permissions': (('view_task', 'Can view task'),),
            },
            bases=(play.models.RolesMixin, models.Model),
        ),
    ]
